### ISSUE TITLE
Installing vanilla kernel - roadmap

### ISSUE THREAD

**Issue by arthurlutz** [wolfallein/clockworkpi-debian#8]
Hi, (sorry for bombarding you with issues, if you prefer having theses discussions on the forum I'm happy to have them there)

What do you imagine could be the roadmap to get clockworkpi to install and upgrade it's kernel from debian repos. 

https://wiki.debian.org/InstallingDebianOn/Allwinner mentions a bunch of unsupported platforms, could we add clockworkpi there ? With the reference to the dtd ? 

From what I understand reading https://wiki.debian.org/MaliGraphics we're using the drivers that are mainline ? I'm not sure I understand what `Mali 4xx: 'utgard' mali-utgard-dkms ` means ? Is there a proprietary driver as an alternative to the mesa lima drivers ? 

What would happen if I did `apt install linux-image-armmp` (5.10 right now) ?

**Comment by wolfallein** [comment]
We probably won't see an "official" kernel from deb repos. 

We just don't have enough devs working on the GameShell, and maintain an official deb package is not as easy as it seems. Seems that devs from clockworkpi (if they have one) are not working on it. The best we could aim is to have our unoficial repo, with our server and we help each other to keep it running and updated.

I'm worried, but clockworkpi seems to have abandoned the GameShell and they are working only on the recently announced DevTerm. We cannot buy any GameShell parts for almost one year and this doesn't seem to change. This behavior completely defeats the modularity they promised from the beginning. My point is that the GameShell community is small and will likely be even smaller if they already stopped production. Attract more developers to work on the board as volunteers will be very difficult from now on.

> From what I understand reading https://wiki.debian.org/MaliGraphics we're using the drivers that are mainline ? I'm not sure I understand what Mali 4xx: 'utgard' mali-utgard-dkms means ? Is there a proprietary driver as an alternative to the mesa lima drivers ?

We are always using the free lima driver. I never tested the proprietary driver, but they exist. I remember that you need to use an old kernel to make it work.

> What would happen if I did apt install linux-image-armmp (5.10 right now) ?

Never tried. Probably nothing will break because the `boot.scr` file selects the correct kernel for the boot, but I don't know.

**Comment by arthurlutz** [comment]
Hye @wolfallein thanks for taking the time to explain all this ! I share your feelings about this being too small of a community, but I wish we can provide some support or building blocks to keep this hardware up to date, exciting and usable. Let's hope some more hardware will come to get this community bigger. I'll keep my eye out on how to be as close as possible to upstream/vanilla.
